# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/.grok/worktrees/zed-base/ab-019c9733-1e7c-7003-90d3-25924f4c127f-a

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/.grok/worktrees/zed-base/ab-019c9733-1e7c-7003-90d3-25924f4c127f-a

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/.grok/worktrees/zed-base/ab-019c9733-1e7c-7003-90d3-25924f4c127f-a/CMakeFiles /root/.grok/worktrees/zed-base/ab-019c9733-1e7c-7003-90d3-25924f4c127f-a//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/.grok/worktrees/zed-base/ab-019c9733-1e7c-7003-90d3-25924f4c127f-a/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named matrix_profile

# Build rule for target.
matrix_profile: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 matrix_profile
.PHONY : matrix_profile

# fast build rule for target.
matrix_profile/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix_profile.dir/build.make CMakeFiles/matrix_profile.dir/build
.PHONY : matrix_profile/fast

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix_profile.dir/build.make CMakeFiles/matrix_profile.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix_profile.dir/build.make CMakeFiles/matrix_profile.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix_profile.dir/build.make CMakeFiles/matrix_profile.dir/src/main.c.s
.PHONY : src/main.c.s

src/matrix.o: src/matrix.c.o
.PHONY : src/matrix.o

# target to build an object file
src/matrix.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix_profile.dir/build.make CMakeFiles/matrix_profile.dir/src/matrix.c.o
.PHONY : src/matrix.c.o

src/matrix.i: src/matrix.c.i
.PHONY : src/matrix.i

# target to preprocess a source file
src/matrix.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix_profile.dir/build.make CMakeFiles/matrix_profile.dir/src/matrix.c.i
.PHONY : src/matrix.c.i

src/matrix.s: src/matrix.c.s
.PHONY : src/matrix.s

# target to generate assembly for a file
src/matrix.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix_profile.dir/build.make CMakeFiles/matrix_profile.dir/src/matrix.c.s
.PHONY : src/matrix.c.s

src/profiler.o: src/profiler.c.o
.PHONY : src/profiler.o

# target to build an object file
src/profiler.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix_profile.dir/build.make CMakeFiles/matrix_profile.dir/src/profiler.c.o
.PHONY : src/profiler.c.o

src/profiler.i: src/profiler.c.i
.PHONY : src/profiler.i

# target to preprocess a source file
src/profiler.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix_profile.dir/build.make CMakeFiles/matrix_profile.dir/src/profiler.c.i
.PHONY : src/profiler.c.i

src/profiler.s: src/profiler.c.s
.PHONY : src/profiler.s

# target to generate assembly for a file
src/profiler.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix_profile.dir/build.make CMakeFiles/matrix_profile.dir/src/profiler.c.s
.PHONY : src/profiler.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... matrix_profile"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/matrix.o"
	@echo "... src/matrix.i"
	@echo "... src/matrix.s"
	@echo "... src/profiler.o"
	@echo "... src/profiler.i"
	@echo "... src/profiler.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

